sudo: required
services:
- docker
cache:
  paths:
    - ccache/

language: generic

notifications:
  email:
    recepients:
      - dengler@toposens.com

env:
  global:
    - DOCKER_IMAGE=toposens/toposens
    - SCRIPT=travis.sh

script:
  - ./$SCRIPT
