sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run -t -d toposens/toposens bash -c "cd /home/toposens && git clone https://github.com/sebdengler/travis-test.git"
  - docker exec $(docker ps -q) bash -c "ls /home/"
  - docker exec $(docker ps -q) bash -c "ls /home/toposens/travis-test/"
  - docker ps
