sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run toposens/toposens
  - docker ps -q
  - docker exec -ti $(docker ps -q) sh -c "ls /opt/ros/"
  - source ros_setup.bash
  - echo "holy guacamolee"
