sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens
  - docker run toposens/toposens -c "ls /opt/ros/"
  - echo "test echo"
  - docker images
  - docker ps -a

script:
  - source ros_setup.bash
  - echo "holy guacamolee"
