sudo: required
services:
- docker
cache: ccache

language: generic

notifications:
  email:
    recepients:
      - dengler@toposens.com
    on_success: always
    on_failure: always

env:
  global:
    - DOCKER_IMAGE=toposens/toposens
    - SCRIPT=travis.sh

script:
  - ./$SCRIPT
