sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run toposens/toposens
  - docker ps -a
  - docker run toposens/toposens /bin/sh -c "ls /opt/ros/"
  - docker ps -a
  - source ros_setup.bash
  - echo "holy guacamolee"
