sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run -t -d toposens/toposens
  - docker ps
  - docker exec $(docker ps -q) ls /opt/ros/
  - docker ps
  - docker exec $(docker ps -q) bash -c "cd /opt/ros/ && ls"
  - docker ps
  - source ros_setup.bash
  - echo "holy guacamolee"
