sudo: required
services:
- docker
cache: ccache
language: generic

notifications:
  email:
    recepients:
      - dengler@toposens.com

env:
  - DOCKER_IMAGE=toposens/toposens

before_script:
  - ln -s . .travis_test

script:
  - .travis_test/travis.sh
