sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - echo "in before_script"
  - ln -s . .travis_test

script:
  - .travis_test/travis.sh
