sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run -t -d toposens/toposens bash -c "git clone https://github.com/sebdengler/travis-test.git && ls"
  - docker exec $(docker ps -q) bash -c "ls"
  - docker exec $(docker ps -q) bash -c "cd /travis-test/ && ls && source ros_setup.bash"
  - docker ps
