sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - docker pull toposens/toposens

script:
  - docker run -t toposens/toposens bash -c "git clone https://github.com/sebdengler/travis-test.git && ls"
  - docker exec $(docker ps -q) ls
  - docker ps
  - source ros_setup.bash
  - echo "holy guacamolee"
