sudo: required
services:
- docker
cache: ccache
language: generic
notifications:
  email:
    recepients:
      - dengler@toposens.com

before_script:
  - echo "in before_script"

script:
  - travis.sh
